import type {Question} from '../data/curriculum';
export type Attempt={questionId:string;topic:string;correct:boolean;answer:string;at:number;rationale?:string};
export type Review={topic:string;due:number;interval:number};
export type Progress={version:1;completed:string[];attempts:Attempt[];reviews:Review[];lastLesson:string;diagnostic:boolean;capstone:null|{answers:Record<string,string>;insights:string;submitted:number;score:number;reflection?:string[]}};
export const emptyProgress=():Progress=>({version:1,completed:[],attempts:[],reviews:[],lastLesson:'inventory',diagnostic:false,capstone:null});
export function grade(q:Question,value:string){if(!value.trim())return false;return typeof q.answer==='number'?Number.isFinite(Number(value.replace(/[$,%\s,]/g,'')))&&Math.abs(Number(value.replace(/[$,%\s,]/g,''))-q.answer)<=(q.tolerance??0.01):value===q.answer;}
export function mastery(p:Progress,topic:string){const latest=new Map<string,Attempt>();p.attempts.filter(a=>a.topic===topic).forEach(a=>latest.set(a.questionId,a));const a=[...latest.values()];return a.length?Math.round(a.filter(a=>a.correct).length/a.length*100):0;}
export function demonstrated(p:Progress,topic:string){return new Set(p.attempts.filter(a=>a.topic===topic).map(a=>a.questionId)).size>=5&&mastery(p,topic)>=80;}
export function state(p:Progress,topic:string){if(p.reviews.some(r=>r.topic===topic&&(r.due<=Date.now()||!demonstrated(p,topic))))return 'Needs review';if(demonstrated(p,topic))return 'Mastered';if(p.attempts.some(a=>a.topic===topic))return 'Practicing';if(p.completed.includes(topic)||p.lastLesson===topic)return 'Learning';return 'Not started';}
export function record(p:Progress,topic:string,q:Question,answer:string,now=Date.now(),rationale?:string):Progress{const correct=grade(q,answer);const attempts=[...p.attempts,{questionId:q.id,topic,correct,answer,at:now,rationale}];let reviews=p.reviews;const existing=reviews.find(r=>r.topic===topic);if(!correct){reviews=[...reviews.filter(r=>r.topic!==topic),{topic,due:now,interval:0}];}else if(existing&&existing.due<=now){const recent=attempts.filter(a=>a.topic===topic&&a.at>=existing.due).slice(-3);const unique=new Set(recent.map(a=>a.questionId));if(recent.length===3&&unique.size===3&&recent.every(a=>a.correct)){const interval=existing.interval===0?1:existing.interval===1?3:7;reviews=[...reviews.filter(r=>r.topic!==topic),{topic,due:now+interval*86400000,interval}];}}
return {...p,attempts,reviews};}
export function closeReview(p:Progress,topic:string,now=Date.now()):Progress{const review=p.reviews.find(r=>r.topic===topic);if(review&&review.interval>=7&&demonstrated(p,topic))return {...p,reviews:p.reviews.filter(r=>r.topic!==topic)};return p;}
export function csv(rows:Record<string,unknown>[]){if(!rows.length)return '';const keys=Object.keys(rows[0]);const cell=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"';return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
export function downloadCSV(name:string,rows:Record<string,unknown>[]){const url=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
