import {test,expect} from '@playwright/test';
import {PROFILE_KEY} from '../src/lib/profile';
import {STORAGE_KEY} from '../src/lib/progress';
import {emptyProgress} from '../src/lib/learning';
test.use({viewport:{width:1440,height:1000}});
test('onboarding, validation, keyboard, profile edits and retained progress',async({page})=>{
const legacy={...emptyProgress(),completed:['inventory'],diagnostic:true};
await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(value));},{key:STORAGE_KEY,value:legacy});
await page.goto('http://127.0.0.1:5173');
await expect(page.getByRole('dialog')).toContainText('Bienvenido a PACE');
await expect(page.getByLabel('Nombre o nombre preferido')).toBeFocused();
await page.screenshot({path:'test-results/onboarding-profile.png'});
await page.getByRole('button',{name:'Continuar',exact:true}).click();
await expect(page.getByRole('alert')).toContainText('Escribe el nombre');
await page.getByLabel('Nombre o nombre preferido').fill('María Fernández');
await page.getByLabel('Área actual').selectOption('reservations');
await page.getByLabel('Objetivo').selectOption('analyst');
await page.keyboard.press('Control+k');
await expect(page.getByRole('dialog')).toContainText('Bienvenido a PACE');
await page.getByRole('button',{name:'Continuar',exact:true}).click();
await expect(page.getByRole('heading',{name:'Todo listo, María Fernández.'})).toBeVisible();
await page.screenshot({path:'test-results/onboarding-workflow.png'});
await page.setViewportSize({width:1280,height:800});
await page.screenshot({path:'test-results/onboarding-1280.png'});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
await page.getByRole('button',{name:'Entrar a PACE'}).click();
await page.reload();await expect(page.getByRole('dialog')).toHaveCount(0);
expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROFILE_KEY)).toMatchObject({name:'María Fernández',role:'reservations',goal:'analyst'});
expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),STORAGE_KEY)).toEqual(legacy);
await page.getByRole('button',{name:'Editar perfil'}).click();
await page.getByLabel('Nombre o nombre preferido').fill('Ana');
await page.getByRole('button',{name:'Guardar perfil'}).click();
await expect(page.getByText('TU SESIÓN · Ana')).toBeVisible();
await page.keyboard.press('Control+k');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');
});
test('onboarding can be skipped with Escape and reopened later',async({page})=>{
await page.goto('http://127.0.0.1:5173');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');
await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await expect(page.getByRole('dialog')).toHaveCount(0);
await page.getByRole('button',{name:'Editar perfil'}).click();await expect(page.getByLabel('Nombre o nombre preferido')).toBeVisible();
await page.getByRole('button',{name:'Ahora no'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
});
