import {useState,useEffect,useRef,type ReactNode} from 'react';
import {Activity,BookOpen,RotateCcw,FlaskConical,Calculator,BookText,BriefcaseBusiness,ChartNoAxesCombined,Search,PanelRightClose,PanelRightOpen,ChevronDown,ChevronRight,Check,Command,Terminal,Download,X,Lock,Clock,CheckCircle2} from 'lucide-react';
import {lessons,modules,findLesson,type Question} from './data/curriculum';
import {formulas} from './data/formulas';
import {glossary,sources} from './data/glossary';
import {diagnostic,interview,forwardDates,reservations,channelMix,capstoneChecks,capstoneRubric} from './data/scenarios';
import {mastery,demonstrated,state,record,grade,emptyProgress,downloadCSV,type Progress} from './lib/learning';
import {loadProgress,saveProgress} from './lib/progress';
import {PracticeLab,Capstone} from './Labs';
import {registerLearningTools} from './lib/webmcp';
const nav=[['Today',Activity],['Curriculum',BookOpen],['Review Queue',RotateCcw],['Practice Lab',FlaskConical],['Formula Sheet',Calculator],['Glossary',BookText],['Interview Lab',BriefcaseBusiness],['Progress',ChartNoAxesCombined]] as const;
export function QuestionForm({q,onAnswer,label='Check answer'}:{q:Question;onAnswer:(v:string,rationale?:string)=>void;label?:string}){const [value,setValue]=useState('');const [sent,setSent]=useState(false);const [reason,setReason]=useState('');const needsReason=q.id.endsWith('-s');const ok=grade(q,value);const options=q.options?[...q.options].sort((a,b)=>{const hash=(s:string)=>[...s+q.id].reduce((n,c)=>(n*31+c.charCodeAt(0))|0,0);return hash(a)-hash(b);}):null;return <form className="question" onSubmit={e=>{e.preventDefault();if(!sent&&value.trim()&&(!needsReason||reason.trim().length>=15)){setSent(true);onAnswer(value,reason);}}}><label className="question-title" htmlFor={q.id}>{q.prompt}</label>{options?<fieldset disabled={sent}><legend className="sr-only">Choose one response</legend>{options.map(o=><label className={'choice '+(value===o?'selected':'')} key={o}><input type="radio" name={q.id} value={o} checked={value===o} onChange={()=>setValue(o)}/><span>{o}</span></label>)}</fieldset>:<div className="answer-line"><input id={q.id} autoComplete="off" inputMode="decimal" value={value} disabled={sent} onChange={e=>setValue(e.target.value)} placeholder="Enter your answer" required/><span className="mono muted">{q.unit}</span></div>}{needsReason&&<label className="reason-label">Defend your decision with evidence<textarea rows={3} disabled={sent} value={reason} onChange={e=>setReason(e.target.value)} placeholder="What evidence supports your action, and what would you monitor?"/><small>At least 15 characters. Compare your reasoning with the feedback; it is not automatically graded.</small></label>}{!sent?<button className="primary" disabled={!value.trim()||(needsReason&&reason.trim().length<15)}>{label}</button>:<div role="status" className={'feedback '+(ok?'correct':'incorrect')}><strong>{ok?'Correct.':'Not quite.'}</strong> {q.explanation}{!ok&&<span className="review-note">Added to your Review Queue. A mistake is useful evidence, not a penalty.</span>}</div>}</form>}
export function SectionTitle({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <header className="section-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</header>}
export function DataTable({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr>{headers.map((h,j)=><th key={h} className={rows.length>0&&rows.every(r=>typeof r[j]==='number'||/^[-+]?\d[\d,.%]*$/.test(String(r[j])))?'numeric':undefined}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className={typeof c==='number'||/^[-+]?\d[\d,.%]*$/.test(String(c))?'numeric':undefined}>{c}</td>)}</tr>)}</tbody></table></div>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{old?.focus();};},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div><div className="modal-body">{children}</div></dialog>}
export default function App(){
const [p,setP]=useState<Progress>(loadProgress);const [view,setView]=useState('Today');const [lessonId,setLessonId]=useState(p.lastLesson);const [step,setStep]=useState(0);const [answered,setAnswered]=useState(false);const [context,setContext]=useState(true);const [tree,setTree]=useState(true);const [modal,setModal]=useState('');const [search,setSearch]=useState('');const [cmd,setCmd]=useState('');const [notice,setNotice]=useState('');const [saved,setSaved]=useState(true);const [reviewId,setReviewId]=useState('');const [sessionKey,setSessionKey]=useState(0);const main=useRef<HTMLElement>(null);
const l=findLesson(lessonId)||lessons[0];const mastered=lessons.filter(x=>demonstrated(p,x.id)).length;const due=p.reviews.filter(r=>r.due<=Date.now());const coreComplete=lessons.every(x=>p.completed.includes(x.id))&&!!p.capstone;const nextLesson=lessons.find(x=>!p.completed.includes(x.id))||l;
useEffect(()=>{setSaved(saveProgress(p));},[p]);
const liveProgress=useRef(p);liveProgress.current=p;useEffect(()=>registerLearningTools(()=>({completed:liveProgress.current.completed,topics:lessons.map(x=>({title:x.title,mastery:mastery(liveProgress.current,x.id),state:state(liveProgress.current,x.id)})),capstoneSubmitted:!!liveProgress.current.capstone})),[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setModal('Search');setSearch('');}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
useEffect(()=>{main.current?.scrollTo(0,0);},[view,lessonId,step]);
const openLesson=(id:string)=>{setLessonId(id);setStep(0);setAnswered(false);setSessionKey(k=>k+1);setView('Lesson');setP(p=>({...p,lastLesson:id}));};
const navigate=(name:string)=>{setSearch('');if(['Formula Sheet','Glossary'].includes(name))setModal(name);else {setView(name);setModal('');}};
const submit=(q:Question,answer:string,topic=l.id,rationale?:string)=>{setP(p=>record(p,topic,q,answer,Date.now(),rationale));setAnswered(true);};
const mixed=p.reviews.map(r=>findLesson(r.topic)).filter(x=>x&&x.id!==l.id)[0]||lessons.filter(x=>p.completed.includes(x.id)&&x.id!==l.id).slice(-1)[0];
const lessonQs=[...l.questions,l.scenario,...(mixed?[mixed.questions[1]]:[])];const currentQ=lessonQs[step-1];
const finish=()=>{setP(p=>({...p,completed:[...new Set([...p.completed,l.id])]}));setModal('Session summary');};
const runCommand=(value:string)=>{const c=value.trim().toLowerCase();setCmd('');if(c==='/next'){if(view==='Lesson'){if(step===0||answered){if(step>=lessonQs.length)finish();else{setStep(s=>s+1);setAnswered(false);}}else setNotice('Commit to an answer before moving on.');}else openLesson(nextLesson.id);}else if(c==='/review')navigate('Review Queue');else if(c==='/formula')navigate('Formula Sheet');else if(c==='/glossary')navigate('Glossary');else if(c==='/progress')navigate('Progress');else if(c==='/practice')navigate('Practice Lab');else if(c==='/reset')setModal('Reset progress');else setNotice('Available: /next /review /formula /glossary /progress /practice /reset');};
const filter=search.toLowerCase();
return <div className={'app '+(!context?'context-hidden':'')}><a className="skip" href="#workspace">Skip to workspace</a><aside className="left-rail"><div className="brand"><img className="brand-logo" src="/brand/pace-logo.png" alt="PACE" width="2203" height="714"/><span>REVENUE ANALYST WORKSPACE</span></div><button className="search-launch" onClick={()=>{setModal('Search');setSearch('');}}><Search size={15}/> Search workspace <kbd>⌘ K</kbd></button><nav aria-label="Primary navigation">{nav.map(([name,Icon])=><button key={name} className={view===name?'nav-item active':'nav-item'} onClick={()=>navigate(name)}><Icon size={17}/><span>{name}</span>{name==='Review Queue'&&due.length>0&&<span className="count">{due.length}</span>}{name==='Interview Lab'&&!coreComplete&&<Lock size={12}/>}</button>)}</nav><button className="tree-toggle" onClick={()=>setTree(!tree)} aria-expanded={tree}>{tree?<ChevronDown size={14}/>:<ChevronRight size={14}/>} LEARNING PATH <span>13 modules</span></button>{tree&&<div className="module-tree">{modules.map((m,i)=><details key={m} open={i===l.module&&view==='Lesson'}><summary onClick={i===0||i===11||i===12?e=>{e.preventDefault();navigate(i===0?'Diagnostic':i===11?'Capstone':'Interview Lab');}:undefined}><span className="module-number">{String(i).padStart(2,'0')}</span><span>{m}</span>{i>0&&i<11&&lessons.filter(x=>x.module===i).every(x=>demonstrated(p,x.id))?<Check size={13}/>:<span className="tree-dot"/>}</summary>{lessons.filter(x=>x.module===i).map(x=><button key={x.id} className={x.id===l.id&&view==='Lesson'?'tree-lesson current':'tree-lesson'} onClick={()=>openLesson(x.id)}>{x.title}<small>{state(p,x.id)}</small></button>)}</details>)}</div>}<div className="rail-footer"><span className="local-dot"/> Local learning profile<small>{saved?'Progress saved on this browser':'Storage unavailable — keep this tab open'}</small></div></aside>
<div className="work-area"><header className="topbar"><div><span className="muted">Workspace</span><ChevronRight size={14}/><span>{view==='Lesson'?`Module ${String(l.module).padStart(2,'0')}`:view}</span></div><div><span className="synthetic-tag">SYNTHETIC RESORT · 900 ROOMS</span><button aria-label={context?'Collapse context rail':'Expand context rail'} onClick={()=>setContext(!context)}>{context?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}</button></div></header>
<main ref={main} id="workspace" tabIndex={-1}>
{view==='Today'&&<><SectionTitle eyebrow="YOUR LEARNING SESSION" title="Build the judgment behind the numbers." description="A practical path from hotel operations to revenue analysis. One concept, one calculation, one decision at a time."/><div className="session-panel"><div className="session-meta"><span className="eyebrow">UP NEXT · MODULE {String(nextLesson.module).padStart(2,'0')}</span><span><Clock size={14}/> About {nextLesson.minutes} min</span></div><h2>{nextLesson.title}</h2><p>{nextLesson.id==='inventory'?'Start with the room night: the unit behind every revenue decision. You already know hotel operations. Now put that knowledge to work analytically.':nextLesson.concept.split('. ')[0]+'.'}</p><div className="session-flow"><span>Learn</span><span>Retrieve</span><span>Calculate</span><span>Decide</span></div><button className="primary" onClick={()=>openLesson(nextLesson.id)}>Continue Session</button>{!p.diagnostic&&<button className="text-button" onClick={()=>navigate('Diagnostic')}>Take the optional 5-question diagnostic</button>}</div><div className="today-grid"><section><div className="eyebrow">REVISIT</div><h3>{due.length?`${due.length} topics ready for review`:'Your review queue is clear'}</h3><p>{due.length?'Revisit weak concepts with fresh retrieval before continuing.':'Incorrect responses will return here. No streaks, no penalties.'}</p><button className="subtle" onClick={()=>navigate('Review Queue')}>Open Review Queue</button></section><section><div className="eyebrow">FOCUS</div><h3>{p.reviews.length?findLesson(p.reviews[0].topic)?.title:'Establish your baseline'}</h3><p>{p.reviews.length?'This concept needs more evidence. Practice explaining the answer, not only calculating it.':'Complete the diagnostic or begin the first lesson to identify your weak concepts.'}</p></section></div><section className="readiness"><div><div className="eyebrow">ANALYST READINESS</div><h3>{mastered} of {lessons.length} topics mastered</h3></div><span className="mono">{Math.round(mastered/lessons.length*100)}%</span><progress value={mastered} max={lessons.length}/><p>Readiness evidence: topic mastery, independent capstone and a reasoned analyst report. Completion alone is not job readiness.</p></section></>}
{view==='Lesson'&&<><div className="lesson-top"><span className="eyebrow">{modules[l.module]}</span><span className="mono muted">{step===0?'CONCEPT':`${step} / ${lessonQs.length} CHECKS`}</span></div><SectionTitle eyebrow={`LESSON ${lessons.indexOf(l)+1} · ${l.minutes} MIN`} title={l.title}/><div className="step-track" aria-label="Learning stages">{['Learn','Calculate','Retrieve','Decide','Mastery'].map((v,i)=><span key={v} className={(step===0?0:step===1?1:step<5?2:step===5?3:4)===i?'on':''}>{String(i+1).padStart(2,'0')} {v}</span>)}</div>{step===0?<><div className="prose"><p>{l.concept}</p></div><div className="formula-block"><span className="eyebrow">THE FRAMEWORK</span><pre>{l.formula}</pre></div><section className="worked"><h3>At the resort</h3><p>{l.example}</p></section><div className="callout"><strong>Watch for this</strong><p>{l.mistake}</p></div>{l.module>=8&&<button className="subtle" onClick={()=>navigate('Practice Lab')}>Open the synthetic analysis tables</button>}<div className="lesson-actions"><span className="muted">Close the reference. Try it from memory.</span><button className="primary" onClick={()=>{setStep(1);setAnswered(false);}}>Start practice</button></div></>:<><div className="exercise-heading"><span className="eyebrow">{step===1?'CALCULATE':step===5?'MAKE A REVENUE DECISION':step>5?'MIXED REVIEW · '+mixed?.title:'RETRIEVE FROM MEMORY'}</span><span className="tag">LOW-STAKES PRACTICE</span></div>{currentQ&&<QuestionForm key={`${sessionKey}-${step}`} q={currentQ} onAnswer={(v,r)=>submit(currentQ,v,step>5?mixed!.id:l.id,r)}/>}<div className="lesson-actions"><button className="subtle" onClick={()=>{setStep(0);setAnswered(false);}}>Revisit concept</button><button className="primary" disabled={!answered} onClick={()=>{if(step===lessonQs.length)finish();else {setStep(s=>s+1);setAnswered(false);}}}>{step===lessonQs.length?'Finish mastery check':'Continue'}</button></div></>}</>}
{view==='Curriculum'&&<><SectionTitle eyebrow="THE LEARNING PATH" title="From operations to analysis" description="Complete in order or jump to a topic. Mastery requires at least five distinct checks and 80% correct current evidence."/><button className="subtle" onClick={()=>navigate('Diagnostic')}>Start diagnostic</button>{modules.slice(1,11).map((m,i)=><section className="curriculum-module" key={m}><h2><span className="mono muted">{String(i+1).padStart(2,'0')}</span> {m}</h2>{lessons.filter(x=>x.module===i+1).map(x=><button className="lesson-row" key={x.id} onClick={()=>openLesson(x.id)}><span>{x.title}<small>{x.minutes} min · calculation, retrieval and decision</small></span><span className={'status '+(demonstrated(p,x.id)?'green':'')}>{state(p,x.id)}</span><ChevronRight size={16}/></button>)}</section>)}<button className="lesson-row" onClick={()=>navigate('Capstone')}><span>11 · Independent capstone</span><ChevronRight size={16}/></button><button className="lesson-row" onClick={()=>navigate('Interview Lab')}><span>12 · Interview Lab</span>{!coreComplete&&<Lock size={15}/>}</button></>}
{view==='Diagnostic'&&<><SectionTitle eyebrow="MODULE 00 · OPTIONAL" title="Start with what you know" description="Five quick checks. These guide acceleration; they never block access or establish mastery by themselves."/>{diagnostic.map((q,i)=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,['occupancy','adr','revpar','pickup','forecast-rooms'][i])}/>)}<button className="primary" onClick={()=>{setP(p=>({...p,diagnostic:true}));setModal('Diagnostic results');}}>See learning recommendations</button><button className="text-button" onClick={()=>openLesson('inventory')}>Skip diagnostic and start learning</button></>}
{view==='Review Queue'&&<><SectionTitle eyebrow="SPACED RETRIEVAL" title="Make weak concepts familiar" description="Missed concepts return immediately, then after roughly 1, 3 and 7 days of successful practice. This is a simple spacing heuristic, not an optimal schedule."/>{!p.reviews.length?<div className="empty-state"><CheckCircle2 size={28}/><h2>No review items yet</h2><p>Incorrect responses appear here automatically. You can also revisit any topic from the curriculum.</p><button className="subtle" onClick={()=>navigate('Curriculum')}>Browse curriculum</button></div>:p.reviews.map(r=><button className="lesson-row" key={r.topic} onClick={()=>{setReviewId(r.topic);setSessionKey(k=>k+1);}}><span>{findLesson(r.topic)?.title}<small>{r.due<=Date.now()?'Due now':`Next review: ${new Date(r.due).toLocaleDateString('en-US')}`}</small></span><span className="mono">{mastery(p,r.topic)}%</span><span>Practice</span></button>)}{reviewId&&<section className="review-session" key={sessionKey}><h2>{findLesson(reviewId).title}</h2><p className="muted">Three different correct answers move this topic to its next review interval.</p>{findLesson(reviewId).questions.slice(0,3).map(q=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,reviewId)}/>)}</section>}</>}
{view==='Practice Lab'&&<PracticeLab onAttempt={(q,v)=>submit(q,v,q.id==='lab-pickup'?'pickup':q.id==='lab-fc'?'forecast-rooms':'excel')}/>}
{view==='Capstone'&&<Capstone progress={p} onSubmit={capstone=>setP(p=>({...p,capstone}))}/>}
{view==='Interview Lab'&&<><SectionTitle eyebrow="MODULE 12" title="Interview Lab" description="Commit to an answer before seeing the explanation. Practice the calculation and the reasoning."/>{!coreComplete?<div className="empty-state"><Lock size={28}/><h2>Build the evidence first</h2><p>Complete all {lessons.length} lessons and submit the independent capstone to unlock the interview lab.</p><p>{p.completed.length} lessons completed · Capstone {p.capstone?'submitted':'not submitted'}</p><button className="primary" onClick={()=>openLesson(nextLesson.id)}>Continue learning</button></div>:interview.map(q=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,'interview')}/>)}</>}
{view==='Progress'&&<><SectionTitle eyebrow="YOUR LEARNING RECORD" title="Completion is not mastery." description="Mastery uses the latest response to each distinct question. At least five different checks and 80% correctness are required. Reviews remain scheduled even as evidence improves."/><div className="metric-strip"><div><span>Completed lessons</span><strong>{p.completed.length}<small> / {lessons.length}</small></strong></div><div><span>Mastered topics</span><strong>{mastered}<small> / {lessons.length}</small></strong></div><div><span>Exercise attempts</span><strong>{p.attempts.length}</strong></div></div>{lessons.map(x=><button className="lesson-row" key={x.id} onClick={()=>openLesson(x.id)}><span>{x.title}<small>{p.completed.includes(x.id)?'Lesson completed':'Lesson not completed'} · {state(p,x.id)}</small></span><progress value={mastery(p,x.id)} max={100}/><span className="mono">{mastery(p,x.id)}%</span></button>)}<h2>Independent capstone</h2><p>{p.capstone?`Submitted · ${p.capstone.score}% objective calculation score. Written judgment requires comparison with the analyst rubric.`:'Not submitted. Your independent report is a separate readiness milestone.'}</p><button className="subtle" onClick={()=>navigate('Capstone')}>Open capstone</button></>}
</main><footer className="composer"><form onSubmit={e=>{e.preventDefault();runCommand(cmd);}}><Terminal size={18}/><label className="sr-only" htmlFor="command-input">Local command</label><input id="command-input" value={cmd} onChange={e=>setCmd(e.target.value)} placeholder="Type a command… /next, /review, /formula"/><button aria-label="Run command"><span className="mono">Enter ↵</span></button></form><div><span>LOCAL COMMANDS · NO AI CHAT</span><span>Ctrl / ⌘ K to navigate</span></div>{notice&&<div role="status" className="command-notice">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={13}/></button></div>}</footer></div>
{context&&<aside className="context-rail"><div className="eyebrow">CONTEXT</div><h2>{view==='Lesson'?'Lesson reference':'Your training resort'}</h2>{view==='Lesson'?<><div className="context-section"><span className="eyebrow">CURRENT MASTERY</span><div className="mastery-value">{mastery(p,l.id)}<span>%</span></div><progress value={mastery(p,l.id)} max={100}/><p>{state(p,l.id)} · target ≥80%</p></div><div className="context-section"><span className="eyebrow">KEY TERMS</span>{l.terms.map(t=><div className="term" key={t}><strong>{t}</strong><p>{glossary[t]||'See the lesson’s worked example.'}</p></div>)}</div><details className="context-section" open={step===0}><summary>Formula reference</summary><pre>{l.formula}</pre></details><details className="context-section"><summary>Common mistake</summary><p>{l.mistake}</p></details><div className="context-section"><span className="eyebrow">RELATED CONCEPTS</span>{lessons.filter(x=>x.id!==l.id&&x.terms.some(t=>l.terms.includes(t))).slice(0,3).map(x=><button className="related" key={x.id} onClick={()=>openLesson(x.id)}>{x.title}</button>)}</div></>:<><div className="resort-label"><span className="mono">RESORT / 001</span><h3>Harbor Point Resort</h3><p>Fictional full-service, all-inclusive resort</p></div><dl className="resort-spec"><div><dt>Inventory</dt><dd>900 rooms</dd></div><div><dt>Currency</dt><dd>USD</dd></div><div><dt>Data source</dt><dd>Synthetic</dd></div></dl><div className="context-section"><span className="eyebrow">REPORTING CONVENTION</span><p>Room revenue is the accommodation allocation, excluding tax and non-room package components.</p><p>All daily examples assume 900 available rooms unless stated otherwise.</p></div><div className="context-section"><span className="eyebrow">THE LEARNING LOOP</span><ol><li>Learn the concept</li><li>Retrieve from memory</li><li>Calculate and interpret</li><li>Make a decision</li><li>Review the evidence</li></ol></div><div className="context-section"><span className="eyebrow">A NOTE ON YOUR DATA</span><p>Every hotel, reservation and result here is invented for training. None represents an actual property.</p></div></>}<button className="source-button" onClick={()=>setModal('Sources and conventions')}>Sources & conventions</button></aside>}
{modal&&<Modal title={modal} onClose={()=>setModal('')}>
{['Search','Glossary','Formula Sheet'].includes(modal)&&<div className="modal-search"><Search size={18}/><input autoFocus aria-label={`Search ${modal}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder={modal==='Search'?'Find a lesson, formula, or workspace…':'Filter reference…'}/></div>}
{modal==='Search'&&<div className="search-results">{[...nav.map(([n])=>({name:n,id:n,kind:'Workspace'})),...lessons.map(x=>({name:x.title,id:x.id,kind:`Module ${x.module}`})),{name:'Independent capstone',id:'Capstone',kind:'Workspace'},{name:'Diagnostic',id:'Diagnostic',kind:'Workspace'}].filter(x=>x.name.toLowerCase().includes(filter)).map(x=><button key={x.id} onClick={()=>{setModal('');if(x.kind==='Workspace')navigate(x.id);else openLesson(x.id);}}><span>{x.name}</span><small>{x.kind}</small></button>)}</div>}
{modal==='Glossary'&&Object.entries(glossary).filter(([k,v])=>(k+' '+v).toLowerCase().includes(filter)).map(([k,v])=><div className="reference-row" key={k}><h3>{k}</h3><p>{v}</p></div>)}
{modal==='Formula Sheet'&&formulas.filter(f=>f.join(' ').toLowerCase().includes(filter)).map(([name,formula,note])=><div className="reference-row" key={name}><h3>{name}</h3><pre>{formula}</pre><p>{note}</p></div>)}
{modal==='Session summary'&&<><div className="summary-score"><span className="eyebrow">LESSON COMPLETED</span><h2>{l.title}</h2><strong>{mastery(p,l.id)}%</strong><p>{demonstrated(p,l.id)?'Mastery demonstrated. Keep applying this concept in later lessons.':'Keep practicing. Completion is recorded; mastery needs more evidence.'}</p></div><p>{p.reviews.some(r=>r.topic===l.id)?'This concept is in your Review Queue. You may continue and revisit it later.':'Related concepts will be mixed into later lessons.'}</p><button className="primary" onClick={()=>{setModal('');const next=lessons[lessons.indexOf(l)+1];if(next)openLesson(next.id);else navigate('Capstone');}}>Continue learning</button><button className="text-button" onClick={()=>navigate('Today')}>Return to Today</button></>}
{modal==='Diagnostic results'&&<><p>A correct diagnostic response suggests you can go directly to practice. It is not sufficient evidence of mastery.</p>{diagnostic.map((q,i)=>{const a=p.attempts.filter(a=>a.questionId===q.id).at(-1);const topic=['occupancy','adr','revpar','pickup','forecast-rooms'][i];return <button className="lesson-row" key={q.id} onClick={()=>{setModal('');openLesson(topic);if(a?.correct)setStep(1);}}><span>{findLesson(topic).title}</span><span>{a?.correct?'Accelerate to practice':'Full instruction'}</span></button>;})}<button className="text-button" onClick={()=>navigate('Today')}>Return to Today</button></>}
{modal==='Reset progress'&&<><p>This removes lesson completion, attempts, review dates and your capstone from this browser. It cannot be undone.</p><button className="danger" onClick={()=>{setP(emptyProgress());setLessonId('inventory');setView('Today');setStep(0);setReviewId('');setModal('');}}>Delete local progress</button><button className="subtle" onClick={()=>setModal('')}>Keep my progress</button></>}
{modal==='Sources and conventions'&&<><p>Original instructional content validated against these industry references. No endorsement or certification is implied.</p>{sources.map(([n,u])=><p key={u}><a href={u} target="_blank" rel="noreferrer">{n}</a></p>)}<p>The STR guide was unavailable during validation. Benchmarking definitions were cross-checked against the EHL guide to hotel STAR reports. Local reporting and contract definitions may differ; always reconcile them.</p><p>All examples use synthetic data, USD and an explicit accommodation allocation. Forecasts are simplified training models. Readiness is evidence of practice, not a guarantee of employment.</p></>}
</Modal>}
</div>;
}




