import {PreferencesControls} from './PreferencesControls';
import {usePreferences,getPreferences} from './lib/preferences';
import {Onboarding} from './Onboarding';
import {createProfile,loadProfile,saveProfile,type Profile} from './lib/profile';
import {es, fold} from './i18n/es';
import {useState,useEffect,useRef,type ReactNode} from 'react';
import {Activity,BookOpen,RotateCcw,FlaskConical,Calculator,BookText,BriefcaseBusiness,ChartNoAxesCombined,Search,PanelRightClose,PanelRightOpen,ChevronDown,ChevronRight,Check,Command,Terminal,Download,X,Lock,Clock,CheckCircle2,UserRound,Menu} from 'lucide-react';
import {lessons,modules,findLesson,type Question} from './data/curriculum';
import {formulas} from './data/formulas';
import {glossary,sources} from './data/glossary';
import {diagnostic,interview,forwardDates,reservations,channelMix,capstoneChecks,capstoneRubric} from './data/scenarios';
import {mastery,demonstrated,state,record,grade,emptyProgress,downloadCSV,type Progress} from './lib/learning';
import {loadProgress,saveProgress} from './lib/progress';
import {PracticeLab,Capstone} from './Labs';
import {registerLearningTools} from './lib/webmcp';
const nav=[['Today',Activity],['Curriculum',BookOpen],['Review Queue',RotateCcw],['Practice Lab',FlaskConical],['Formula Sheet',Calculator],['Glossary',BookText],['Interview Lab',BriefcaseBusiness],['Progress',ChartNoAxesCombined]] as const;
export function QuestionForm({q,onAnswer,label='Check answer'}:{q:Question;onAnswer:(v:string,rationale?:string)=>void;label?:string}){const [value,setValue]=useState('');const [sent,setSent]=useState(false);const [reason,setReason]=useState('');const needsReason=q.id.endsWith('-s');const ok=grade(q,value);const options=q.options?[...q.options].sort((a,b)=>{const hash=(s:string)=>[...s+q.id].reduce((n,c)=>(n*31+c.charCodeAt(0))|0,0);return hash(a)-hash(b);}):null;return <form className="question" onSubmit={e=>{e.preventDefault();if(!sent&&value.trim()&&(!needsReason||reason.trim().length>=15)){setSent(true);onAnswer(value,reason);}}}><label className="question-title" htmlFor={q.id}>{es(q.prompt)}</label>{es(options?<fieldset disabled={sent}><legend className="sr-only">{es("Choose one response")}</legend>{es(options.map(o=><label className={'choice '+(value===o?'selected':'')} key={o}><input type="radio" name={q.id} value={o} checked={value===o} onChange={()=>setValue(o)}/><span>{es(o)}</span></label>))}</fieldset>:<div className="answer-line"><input id={q.id} autoComplete="off" inputMode="decimal" value={value} disabled={sent} onChange={e=>setValue(e.target.value)} placeholder={es("Enter your answer")} required/><span className="mono muted">{es(q.unit)}</span></div>)}{es(needsReason&&<label className="reason-label">{es("Defend your decision with evidence")}<textarea rows={3} disabled={sent} value={reason} onChange={e=>setReason(e.target.value)} placeholder={es("What evidence supports your action, and what would you monitor?")}/><small>{es("At least 15 characters. Compare your reasoning with the feedback; it is not automatically graded.")}</small></label>)}{es(!sent?<button className="primary" disabled={!value.trim()||(needsReason&&reason.trim().length<15)}>{es(label)}</button>:<div role="status" className={'feedback '+(ok?'correct':'incorrect')}><strong>{es(ok?'Correct.':'Not quite.')}</strong> {es(q.explanation)}{es(!ok&&<span className="review-note">{es("Added to your Review Queue. A mistake is useful evidence, not a penalty.")}</span>)}</div>)}</form>}
export function SectionTitle({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <header className="section-title"><div className="eyebrow">{es(eyebrow)}</div><h1>{es(title)}</h1>{es(description&&<p>{es(description)}</p>)}</header>}
export function DataTable({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="table-scroll" tabIndex={0} aria-label={es("Scrollable data table")}><table><thead><tr>{es(headers.map((h,j)=><th key={h} className={rows.length>0&&rows.every(r=>typeof r[j]==='number'||/^[-+]?\d[\d,.%]*$/.test(String(r[j])))?'numeric':undefined}>{es(h)}</th>))}</tr></thead><tbody>{es(rows.map((r,i)=><tr key={i}>{es(r.map((c,j)=><td key={j} className={typeof c==='number'||/^[-+]?\d[\d,.%]*$/.test(String(c))?'numeric':/^\d{4}-\d{2}-\d{2}$/.test(String(c))?'date-value':undefined}>{es(c)}</td>))}</tr>))}</tbody></table></div>}
function Modal({title,children,onClose,className}:{title:string;children:ReactNode;onClose:()=>void;className?:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;const dialog=ref.current;dialog?.showModal();(dialog?.querySelector<HTMLElement>('input,textarea')||dialog?.querySelector<HTMLElement>('select'))?.focus();return()=>{dialog?.close();old?.focus();};},[]);return <dialog ref={ref} className={className} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{es(title)}</h2><button aria-label={es("Close dialog")} onClick={onClose}><X size={18}/></button></div><div className="modal-body">{es(children)}</div></dialog>}
export default function App(){
usePreferences();
const [compact,setCompact]=useState(()=>window.matchMedia('(max-width:1000px)').matches);
const [profile,setProfile]=useState<Profile|null>(loadProfile);const [profileSaved,setProfileSaved]=useState(true);const [p,setP]=useState<Progress>(loadProgress);const [view,setView]=useState('Today');const [lessonId,setLessonId]=useState(p.lastLesson);const [step,setStep]=useState(0);const [answered,setAnswered]=useState(false);const [context,setContext]=useState(true);const [tree,setTree]=useState(true);const [modal,setModal]=useState(()=>profile?'':'Onboarding');const [search,setSearch]=useState('');const [cmd,setCmd]=useState('');const [notice,setNotice]=useState('');const [saved,setSaved]=useState(true);const [reviewId,setReviewId]=useState('');const [sessionKey,setSessionKey]=useState(0);const main=useRef<HTMLElement>(null);
useEffect(()=>{const query=window.matchMedia('(max-width:1000px)');const resize=()=>{setCompact(query.matches);if(!query.matches)setModal(value=>['Navigation','Context'].includes(value)?'':value);};query.addEventListener('change',resize);return()=>query.removeEventListener('change',resize);},[]);
const l=findLesson(lessonId)||lessons[0];const mastered=lessons.filter(x=>demonstrated(p,x.id)).length;const due=p.reviews.filter(r=>r.due<=Date.now());const coreComplete=lessons.every(x=>p.completed.includes(x.id))&&!!p.capstone;const nextLesson=lessons.find(x=>!p.completed.includes(x.id))||l;
useEffect(()=>{setSaved(saveProgress(p));},[p]);
const liveProgress=useRef(p);liveProgress.current=p;useEffect(()=>registerLearningTools(()=>({completed:liveProgress.current.completed,topics:lessons.map(x=>({title:es(x.title),mastery:mastery(liveProgress.current,x.id),state:es(state(liveProgress.current,x.id))})),capstoneSubmitted:!!liveProgress.current.capstone})),[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(modal==='Onboarding')return;setModal('Search');setSearch('');}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[modal]);
useEffect(()=>{main.current?.scrollTo(0,0);},[view,lessonId,step]);
const openLesson=(id:string)=>{setModal('');setLessonId(id);setStep(0);setAnswered(false);setSessionKey(k=>k+1);setView('Lesson');setP(p=>({...p,lastLesson:id}));};
const navigate=(name:string)=>{setSearch('');if(['Formula Sheet','Glossary'].includes(name))setModal(name);else {setView(name);setModal('');}};
const submit=(q:Question,answer:string,topic=l.id,rationale?:string)=>{setP(p=>record(p,topic,q,answer,Date.now(),rationale));setAnswered(true);};
const mixed=p.reviews.map(r=>findLesson(r.topic)).filter(x=>x&&x.id!==l.id)[0]||lessons.filter(x=>p.completed.includes(x.id)&&x.id!==l.id).slice(-1)[0];
const lessonQs=[...l.questions,l.scenario,...(mixed?[mixed.questions[1]]:[])];const currentQ=lessonQs[step-1];
const finish=()=>{setP(p=>({...p,completed:[...new Set([...p.completed,l.id])]}));setModal('Session summary');};
const runCommand=(value:string)=>{const c=value.trim().toLowerCase();setCmd('');if(c==='/next'){if(view==='Lesson'){if(step===0||answered){if(step>=lessonQs.length)finish();else{setStep(s=>s+1);setAnswered(false);}}else setNotice('Commit to an answer before moving on.');}else openLesson(nextLesson.id);}else if(c==='/review')navigate('Review Queue');else if(c==='/formula')navigate('Formula Sheet');else if(c==='/glossary')navigate('Glossary');else if(c==='/progress')navigate('Progress');else if(c==='/practice')navigate('Practice Lab');else if(c==='/reset')setModal('Reset progress');else setNotice('Available: /next /review /formula /glossary /progress /practice /reset');};
const filter=fold(search);
const finishProfile=(value:Profile,start:boolean)=>{setProfile(value);setProfileSaved(saveProfile(value));setModal('');if(start)setView('Today');};const closeModal=()=>{if(modal==='Onboarding'&&!profile)finishProfile(createProfile(),false);else setModal('');};
const navigationRail=<aside className="left-rail"><div className="brand"><img className="brand-logo" src="/brand/pace-logo.png" alt={es("PACE")} width="2203" height="714"/><span>{es("REVENUE ANALYST WORKSPACE")}</span></div><button className="search-launch" onClick={()=>{setModal('Search');setSearch('');}}><Search size={15}/>{es(" Search workspace ")}<kbd>{es("⌘ K")}</kbd></button><nav aria-label={es("Primary navigation")}>{es(nav.map(([name,Icon])=><button key={name} aria-label={es(name)} className={view===name?'nav-item active':'nav-item'} onClick={()=>navigate(name)}><Icon size={17}/><span>{es(name)}</span>{es(name==='Review Queue'&&due.length>0&&<span className="count">{es(due.length)}</span>)}{es(name==='Interview Lab'&&!coreComplete&&<Lock size={12}/>)}</button>))}</nav><button className="tree-toggle" onClick={()=>setTree(!tree)} aria-expanded={tree}>{es(tree?<ChevronDown size={14}/>:<ChevronRight size={14}/>)}{es(" LEARNING PATH ")}<span>{es("13 modules")}</span></button>{es(tree&&<div className="module-tree">{es(modules.map((m,i)=><details key={m} open={i===l.module&&view==='Lesson'}><summary onClick={i===0||i===11||i===12?e=>{e.preventDefault();navigate(i===0?'Diagnostic':i===11?'Capstone':'Interview Lab');}:undefined}><span className="module-number">{es(String(i).padStart(2,'0'))}</span><span>{es(m)}</span>{es(i>0&&i<11&&lessons.filter(x=>x.module===i).every(x=>demonstrated(p,x.id))?<Check size={13}/>:<span className="tree-dot"/>)}</summary>{es(lessons.filter(x=>x.module===i).map(x=><button key={x.id} className={x.id===l.id&&view==='Lesson'?'tree-lesson current':'tree-lesson'} onClick={()=>openLesson(x.id)}>{es(x.title)}<small>{es(state(p,x.id))}</small></button>))}</details>))}</div>)}<div className="rail-footer"><button className="profile-launch" onClick={()=>setModal('Onboarding')} aria-label={es("Edit profile")}><UserRound size={16}/><span>{profile?.name||es('Your profile')}</span></button>{!profileSaved&&<small role="status">{es('Your profile could not be saved. It is available for this session only.')}</small>}<span className="local-dot"/>{es(" Local learning profile")}<small>{es(saved?'Progress saved on this browser':'Storage unavailable — keep this tab open')}</small></div></aside>;
const contextRail=<aside className="context-rail"><div className="eyebrow">{es("CONTEXT")}</div><h2>{es(view==='Lesson'?'Lesson reference':'Your training resort')}</h2>{es(view==='Lesson'?<><div className="context-section"><span className="eyebrow">{es("CURRENT MASTERY")}</span><div className="mastery-value">{es(mastery(p,l.id))}<span>{es("%")}</span></div><progress value={mastery(p,l.id)} max={100}/><p>{es(state(p,l.id))}{es(" · target ≥80%")}</p></div><div className="context-section"><span className="eyebrow">{es("KEY TERMS")}</span>{es(l.terms.map(t=><div className="term" key={t}><strong>{es(t)}</strong><p>{es(glossary[t]||'See the lesson’s worked example.')}</p></div>))}</div><details className="context-section" open={step===0}><summary>{es("Formula reference")}</summary><pre>{es(l.formula)}</pre></details><details className="context-section"><summary>{es("Common mistake")}</summary><p>{es(l.mistake)}</p></details><div className="context-section"><span className="eyebrow">{es("RELATED CONCEPTS")}</span>{es(lessons.filter(x=>x.id!==l.id&&x.terms.some(t=>l.terms.includes(t))).slice(0,3).map(x=><button className="related" key={x.id} onClick={()=>openLesson(x.id)}>{es(x.title)}</button>))}</div></>:<><div className="resort-label"><span className="mono">{es("RESORT / 001")}</span><h3>{es("Harbor Point Resort")}</h3><p>{es("Fictional full-service, all-inclusive resort")}</p></div><dl className="resort-spec"><div><dt>{es("Inventory")}</dt><dd>{es("900 rooms")}</dd></div><div><dt>{es("Currency")}</dt><dd>{es("USD")}</dd></div><div><dt>{es("Data source")}</dt><dd>{es("Synthetic")}</dd></div></dl><div className="context-section"><span className="eyebrow">{es("REPORTING CONVENTION")}</span><p>{es("Room revenue is the accommodation allocation, excluding tax and non-room package components.")}</p><p>{es("All daily examples assume 900 available rooms unless stated otherwise.")}</p></div><div className="context-section"><span className="eyebrow">{es("THE LEARNING LOOP")}</span><ol><li>{es("Learn the concept")}</li><li>{es("Retrieve from memory")}</li><li>{es("Calculate and interpret")}</li><li>{es("Make a decision")}</li><li>{es("Review the evidence")}</li></ol></div><div className="context-section"><span className="eyebrow">{es("A NOTE ON YOUR DATA")}</span><p>{es("Every hotel, reservation and result here is invented for training. None represents an actual property.")}</p></div></>)}<button className="source-button" onClick={()=>setModal('Sources and conventions')}>{es("Sources & conventions")}</button></aside>;
return <div className={'app '+(!context?'context-hidden':'')}><a className="skip" href="#workspace">{es("Skip to workspace")}</a>{navigationRail}
<div className="work-area"><header className="topbar"><div><button className="mobile-only" aria-label={es("Open navigation")} aria-haspopup="dialog" onClick={()=>setModal('Navigation')}><Menu size={20}/></button><img className="mobile-only mobile-brand-logo" src="/brand/pace-logo.png" alt="PACE" width="2203" height="714"/><span className="muted">{es("Workspace")}</span><ChevronRight size={14}/><span>{es(view==='Lesson'?`Module ${String(l.module).padStart(2,'0')}`:view)}</span></div><div><button className="mobile-only mobile-search" aria-label={es("Open search")} aria-haspopup="dialog" onClick={()=>{setModal('Search');setSearch('');}}><Search size={18}/></button><PreferencesControls/><span className="synthetic-tag">{es("SYNTHETIC RESORT · 900 ROOMS")}</span><button aria-label={es(compact?'Open context panel':context?'Collapse context rail':'Expand context rail')} onClick={()=>compact?setModal('Context'):setContext(!context)}>{es(context?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>)}</button></div></header>
<main ref={main} id="workspace" tabIndex={-1}>
{es(view==='Today'&&<><SectionTitle eyebrow={profile?.name?`${es('YOUR SESSION')} · ${profile.name}`:es("YOUR LEARNING SESSION")} title={es("Build the judgment behind the numbers.")} description={es("A practical path from hotel operations to revenue analysis. One concept, one calculation, one decision at a time.")}/><div className="session-panel"><div className="session-meta"><span className="eyebrow">{es("UP NEXT · MODULE ")}{es(String(nextLesson.module).padStart(2,'0'))}</span><span><Clock size={14}/>{es(" About ")}{es(nextLesson.minutes)}{es(" min")}</span></div><h2>{es(nextLesson.title)}</h2><p>{es(nextLesson.id==='inventory'?'Start with the room night: the unit behind every revenue decision. You already know hotel operations. Now put that knowledge to work analytically.':nextLesson.concept.split('. ')[0]+'.')}</p><div className="session-flow"><span>{es("Learn")}</span><span>{es("Retrieve")}</span><span>{es("Calculate")}</span><span>{es("Decide")}</span></div><button className="primary" onClick={()=>openLesson(nextLesson.id)}>{es("Continue Session")}</button>{es(!p.diagnostic&&<button className="text-button" onClick={()=>navigate('Diagnostic')}>{es("Take the optional 5-question diagnostic")}</button>)}</div><div className="today-grid"><section><div className="eyebrow">{es("REVISIT")}</div><h3>{es(due.length?`${due.length} topics ready for review`:'Your review queue is clear')}</h3><p>{es(due.length?'Revisit weak concepts with fresh retrieval before continuing.':'Incorrect responses will return here. No streaks, no penalties.')}</p><button className="subtle" onClick={()=>navigate('Review Queue')}>{es("Open Review Queue")}</button></section><section><div className="eyebrow">{es("FOCUS")}</div><h3>{es(p.reviews.length?findLesson(p.reviews[0].topic)?.title:'Establish your baseline')}</h3><p>{es(p.reviews.length?'This concept needs more evidence. Practice explaining the answer, not only calculating it.':'Complete the diagnostic or begin the first lesson to identify your weak concepts.')}</p></section></div><section className="readiness"><div><div className="eyebrow">{es("ANALYST READINESS")}</div><h3>{es(mastered)}{es(" of ")}{es(lessons.length)}{es(" topics mastered")}</h3></div><span className="mono">{es(Math.round(mastered/lessons.length*100))}{es("%")}</span><progress value={mastered} max={lessons.length}/><p>{es("Readiness evidence: topic mastery, independent capstone and a reasoned analyst report. Completion alone is not job readiness.")}</p></section></>)}
{es(view==='Lesson'&&<><div className="lesson-top"><span className="eyebrow">{es(modules[l.module])}</span><span className="mono muted">{es(step===0?'CONCEPT':`${step} / ${lessonQs.length} CHECKS`)}</span></div><SectionTitle eyebrow={es(`LESSON ${lessons.indexOf(l)+1} · ${l.minutes} MIN`)} title={es(l.title)}/><div className="step-track" aria-label={es("Learning stages")}>{es(['Learn','Calculate','Retrieve','Decide','Mastery'].map((v,i)=><span key={v} className={(step===0?0:step===1?1:step<5?2:step===5?3:4)===i?'on':''}>{es(String(i+1).padStart(2,'0'))} {es(v)}</span>))}</div>{es(step===0?<><div className="prose"><p>{es(l.concept)}</p></div><div className="formula-block"><span className="eyebrow">{es("THE FRAMEWORK")}</span><pre>{es(l.formula)}</pre></div><section className="worked"><h3>{es("At the resort")}</h3><p>{es(l.example)}</p></section><div className="callout"><strong>{es("Watch for this")}</strong><p>{es(l.mistake)}</p></div>{es(l.module>=8&&<button className="subtle" onClick={()=>navigate('Practice Lab')}>{es("Open the synthetic analysis tables")}</button>)}<div className="lesson-actions"><span className="muted">{es("Close the reference. Try it from memory.")}</span><button className="primary" onClick={()=>{setStep(1);setAnswered(false);}}>{es("Start practice")}</button></div></>:<><div className="exercise-heading"><span className="eyebrow">{es(step===1?'CALCULATE':step===5?'MAKE A REVENUE DECISION':step>5?'MIXED REVIEW · '+mixed?.title:'RETRIEVE FROM MEMORY')}</span><span className="tag">{es("LOW-STAKES PRACTICE")}</span></div>{es(currentQ&&<QuestionForm key={`${sessionKey}-${step}`} q={currentQ} onAnswer={(v,r)=>submit(currentQ,v,step>5?mixed!.id:l.id,r)}/>)}<div className="lesson-actions"><button className="subtle" onClick={()=>{setStep(0);setAnswered(false);}}>{es("Revisit concept")}</button><button className="primary" disabled={!answered} onClick={()=>{if(step===lessonQs.length)finish();else {setStep(s=>s+1);setAnswered(false);}}}>{es(step===lessonQs.length?'Finish mastery check':'Continue')}</button></div></>)}</>)}
{es(view==='Curriculum'&&<><SectionTitle eyebrow={es("THE LEARNING PATH")} title={es("From operations to analysis")} description={es("Complete in order or jump to a topic. Mastery requires at least five distinct checks and 80% correct current evidence.")}/><button className="subtle" onClick={()=>navigate('Diagnostic')}>{es("Start diagnostic")}</button>{es(modules.slice(1,11).map((m,i)=><section className="curriculum-module" key={m}><h2><span className="mono muted">{es(String(i+1).padStart(2,'0'))}</span> {es(m)}</h2>{es(lessons.filter(x=>x.module===i+1).map(x=><button className="lesson-row" key={x.id} onClick={()=>openLesson(x.id)}><span>{es(x.title)}<small>{es(x.minutes)}{es(" min · calculation, retrieval and decision")}</small></span><span className={'status '+(demonstrated(p,x.id)?'green':'')}>{es(state(p,x.id))}</span><ChevronRight size={16}/></button>))}</section>))}<button className="lesson-row" onClick={()=>navigate('Capstone')}><span>{es("11 · Independent capstone")}</span><ChevronRight size={16}/></button><button className="lesson-row" onClick={()=>navigate('Interview Lab')}><span>{es("12 · Interview Lab")}</span>{es(!coreComplete&&<Lock size={15}/>)}</button></>)}
{es(view==='Diagnostic'&&<><SectionTitle eyebrow={es("MODULE 00 · OPTIONAL")} title={es("Start with what you know")} description={es("Five quick checks. These guide acceleration; they never block access or establish mastery by themselves.")}/>{es(diagnostic.map((q,i)=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,['occupancy','adr','revpar','pickup','forecast-rooms'][i])}/>))}<button className="primary" onClick={()=>{setP(p=>({...p,diagnostic:true}));setModal('Diagnostic results');}}>{es("See learning recommendations")}</button><button className="text-button" onClick={()=>openLesson('inventory')}>{es("Skip diagnostic and start learning")}</button></>)}
{es(view==='Review Queue'&&<><SectionTitle eyebrow={es("SPACED RETRIEVAL")} title={es("Make weak concepts familiar")} description={es("Missed concepts return immediately, then after roughly 1, 3 and 7 days of successful practice. This is a simple spacing heuristic, not an optimal schedule.")}/>{es(!p.reviews.length?<div className="empty-state"><CheckCircle2 size={28}/><h2>{es("No review items yet")}</h2><p>{es("Incorrect responses appear here automatically. You can also revisit any topic from the curriculum.")}</p><button className="subtle" onClick={()=>navigate('Curriculum')}>{es("Browse curriculum")}</button></div>:p.reviews.map(r=><button className="lesson-row" key={r.topic} onClick={()=>{setReviewId(r.topic);setSessionKey(k=>k+1);}}><span>{es(findLesson(r.topic)?.title)}<small>{es(r.due<=Date.now()?'Due now':`Next review: ${new Date(r.due).toLocaleDateString(getPreferences().language==='es'?'es-MX':'en-US')}`)}</small></span><span className="mono">{es(mastery(p,r.topic))}{es("%")}</span><span>{es("Practice")}</span></button>))}{es(reviewId&&<section className="review-session" key={sessionKey}><h2>{es(findLesson(reviewId).title)}</h2><p className="muted">{es("Three different correct answers move this topic to its next review interval.")}</p>{es(findLesson(reviewId).questions.slice(0,3).map(q=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,reviewId)}/>))}</section>)}</>)}
{es(view==='Practice Lab'&&<PracticeLab onAttempt={(q,v)=>submit(q,v,q.id==='lab-pickup'?'pickup':q.id==='lab-fc'?'forecast-rooms':'excel')}/>)}
{es(view==='Capstone'&&<Capstone progress={p} onSubmit={capstone=>setP(p=>({...p,capstone}))}/>)}
{es(view==='Interview Lab'&&<><SectionTitle eyebrow={es("MODULE 12")} title={es("Interview Lab")} description={es("Commit to an answer before seeing the explanation. Practice the calculation and the reasoning.")}/>{es(!coreComplete?<div className="empty-state"><Lock size={28}/><h2>{es("Build the evidence first")}</h2><p>{es("Complete all ")}{es(lessons.length)}{es(" lessons and submit the independent capstone to unlock the interview lab.")}</p><p>{es(p.completed.length+" lessons completed · Capstone")} {es(p.capstone?'submitted':'not submitted')}</p><button className="primary" onClick={()=>openLesson(nextLesson.id)}>{es("Continue learning")}</button></div>:interview.map(q=><QuestionForm key={q.id} q={q} onAnswer={v=>submit(q,v,'interview')}/>))}</>)}
{es(view==='Progress'&&<><SectionTitle eyebrow={es("YOUR LEARNING RECORD")} title={es("Completion is not mastery.")} description={es("Mastery uses the latest response to each distinct question. At least five different checks and 80% correctness are required. Reviews remain scheduled even as evidence improves.")}/><div className="metric-strip"><div><span>{es("Completed lessons")}</span><strong>{es(p.completed.length)}<small>{es(" / ")}{es(lessons.length)}</small></strong></div><div><span>{es("Mastered topics")}</span><strong>{es(mastered)}<small>{es(" / ")}{es(lessons.length)}</small></strong></div><div><span>{es("Exercise attempts")}</span><strong>{es(p.attempts.length)}</strong></div></div>{es(lessons.map(x=><button className="lesson-row" key={x.id} onClick={()=>openLesson(x.id)}><span>{es(x.title)}<small>{es(p.completed.includes(x.id)?'Lesson completed':'Lesson not completed')}{es(" · ")}{es(state(p,x.id))}</small></span><progress value={mastery(p,x.id)} max={100}/><span className="mono">{es(mastery(p,x.id))}{es("%")}</span></button>))}<h2>{es("Independent capstone")}</h2><p>{es(p.capstone?`Submitted · ${p.capstone.score}% objective calculation score. Written judgment requires comparison with the analyst rubric.`:'Not submitted. Your independent report is a separate readiness milestone.')}</p><button className="subtle" onClick={()=>navigate('Capstone')}>{es("Open capstone")}</button></>)}
</main><footer className="composer"><form onSubmit={e=>{e.preventDefault();runCommand(cmd);}}><Terminal size={18}/><label className="sr-only" htmlFor="command-input">{es("Local command")}</label><input id="command-input" value={cmd} onChange={e=>setCmd(e.target.value)} placeholder={es("Type a command… /next, /review, /formula")}/><button aria-label={es("Run command")}><span className="mono">{es("Enter ↵")}</span></button></form><div><span>{es("LOCAL COMMANDS · NO AI CHAT")}</span><span>{es("Ctrl / ⌘ K to navigate")}</span></div>{es(notice&&<div role="status" className="command-notice">{es(notice)}<button aria-label={es("Dismiss message")} onClick={()=>setNotice('')}><X size={13}/></button></div>)}</footer></div>
{es(context&&contextRail)}
{es(modal&&<Modal title={modal==='Onboarding'?es(profile?.name?'Your profile':'Welcome to PACE'):es(modal)} onClose={closeModal} className={modal==='Navigation'?'navigation-dialog':modal==='Context'?'context-dialog':undefined}>
{modal==='Navigation'&&navigationRail}
{modal==='Context'&&contextRail}
{modal==='Onboarding'&&<Onboarding profile={profile} onSave={finishProfile} onSkip={closeModal}/>}
{es(['Search','Glossary','Formula Sheet'].includes(modal)&&<div className="modal-search"><Search size={18}/><input autoFocus aria-label={es(`Search ${modal}`)} value={search} onChange={e=>setSearch(e.target.value)} placeholder={es(modal==='Search'?'Find a lesson, formula, or workspace…':'Filter reference…')}/></div>)}
{es(modal==='Search'&&<div className="search-results">{es([...nav.map(([n])=>({name:n,id:n,kind:'Workspace'})),...lessons.map(x=>({name:x.title,id:x.id,kind:`Module ${x.module}`})),{name:'Independent capstone',id:'Capstone',kind:'Workspace'},{name:'Diagnostic',id:'Diagnostic',kind:'Workspace'}].filter(x=>fold(es(x.name)).includes(filter)).map(x=><button key={x.id} onClick={()=>{setModal('');if(x.kind==='Workspace')navigate(x.id);else openLesson(x.id);}}><span>{es(x.name)}</span><small>{es(x.kind)}</small></button>))}</div>)}
{es(modal==='Glossary'&&Object.entries(glossary).filter(([k,v])=>fold(es(k)+' '+es(v)).includes(filter)).map(([k,v])=><div className="reference-row" key={k}><h3>{es(k)}</h3><p>{es(v)}</p></div>))}
{es(modal==='Formula Sheet'&&formulas.filter(f=>fold(f.map(es).join(' ')).includes(filter)).map(([name,formula,note])=><div className="reference-row" key={name}><h3>{es(name)}</h3><pre>{es(formula)}</pre><p>{es(note)}</p></div>))}
{es(modal==='Session summary'&&<><div className="summary-score"><span className="eyebrow">{es("LESSON COMPLETED")}</span><h2>{es(l.title)}</h2><strong>{es(mastery(p,l.id))}{es("%")}</strong><p>{es(demonstrated(p,l.id)?'Mastery demonstrated. Keep applying this concept in later lessons.':'Keep practicing. Completion is recorded; mastery needs more evidence.')}</p></div><p>{es(p.reviews.some(r=>r.topic===l.id)?'This concept is in your Review Queue. You may continue and revisit it later.':'Related concepts will be mixed into later lessons.')}</p><button className="primary" onClick={()=>{setModal('');const next=lessons[lessons.indexOf(l)+1];if(next)openLesson(next.id);else navigate('Capstone');}}>{es("Continue learning")}</button><button className="text-button" onClick={()=>navigate('Today')}>{es("Return to Today")}</button></>)}
{es(modal==='Diagnostic results'&&<><p>{es("A correct diagnostic response suggests you can go directly to practice. It is not sufficient evidence of mastery.")}</p>{es(diagnostic.map((q,i)=>{const a=p.attempts.filter(a=>a.questionId===q.id).at(-1);const topic=['occupancy','adr','revpar','pickup','forecast-rooms'][i];return <button className="lesson-row" key={q.id} onClick={()=>{setModal('');openLesson(topic);if(a?.correct)setStep(1);}}><span>{es(findLesson(topic).title)}</span><span>{es(a?.correct?'Accelerate to practice':'Full instruction')}</span></button>;}))}<button className="text-button" onClick={()=>navigate('Today')}>{es("Return to Today")}</button></>)}
{es(modal==='Reset progress'&&<><p>{es("This removes lesson completion, attempts, review dates and your capstone from this browser. It cannot be undone.")}</p><button className="danger" onClick={()=>{setP(emptyProgress());setLessonId('inventory');setView('Today');setStep(0);setReviewId('');setModal('');}}>{es("Delete local progress")}</button><button className="subtle" onClick={()=>setModal('')}>{es("Keep my progress")}</button></>)}
{es(modal==='Sources and conventions'&&<><p>{es("Original instructional content validated against these industry references. No endorsement or certification is implied.")}</p>{es(sources.map(([n,u])=><p key={u}><a href={u} target="_blank" rel="noreferrer">{es(n)}</a></p>))}<p>{es("The STR guide was unavailable during validation. Benchmarking definitions were cross-checked against the EHL guide to hotel STAR reports. Local reporting and contract definitions may differ; always reconcile them.")}</p><p>{es("All examples use synthetic data, USD and an explicit accommodation allocation. Forecasts are simplified training models. Readiness is evidence of practice, not a guarantee of employment.")}</p></>)}
</Modal>)}
</div>;
}




